name: Auto Pause Leishen

on:
  schedule:
    # 自动暂停时间 (UTC时间20:00 = 北京时间4:00)
    - cron: '23 11 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  actions: write
  contents: write

jobs:
  pause:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Run Leishen Auto Pause
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: go run main.go

    - name: Keep workflow alive
      if: always()
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        workflow_id=$(gh api repos/${{ github.repository }}/actions/workflows --jq '.workflows[] | select(.name == "${{ github.workflow }}") | .id')
        gh api -X PUT "repos/${{github.repository}}/actions/workflows/${workflow_id}/enable"
